### PR TITLE
Use less powerful kills if possible

### PR DESCRIPTION
**Pull request by JuanCanham**

### CODE REVIEW

**Comment by forslund** [comment]
Hi this looks like a much more sane approach than the previous -9 approach. Will give it a test go in a bit. In the meantime it would be great if you could sign our Contributor License Agreement

To protect yourself, the project, and users of Mycroft technologies we require a Contributor Licensing Agreement (CLA) before accepting any code contribution. This agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.
 
Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by forslund** [comment]
Works nicely :+1:, I'll merge as soon as the CLA has been signed

**Comment by JuanCanham** [comment]
Hi, sorry wasn't expecting the quick response, I've filled out the the CLA form but haven't been emailed a form to fill out yet. is just the https://mycroft.ai/cla enough, or should i wait until I get emailed something.

**Comment by forslund** [comment]
You should recieve an form in your mail, there was some troubles recently and some e-mails weren't sent. I'll look into it (or rather, ask @krisgesling to look into it)

**Comment by krisgesling** [comment]
CLA received, thanks for the great contribution Juan!

**Pull request merged**
